#!/usr/bin/env python3
"""Generate CYK parsing benchmark inputs.

Produces in <out-dir>:
  input.bin             N bytes, each in [0, N_SIGMA), LCG seed=42.
  grammar.bin           Header + produce[N_NT*N_NT] (Word64) + produce_term[N_SIGMA] (Word64).
                        Grammar generated by LCG with a separate seed; calibrated so that
                        a small probe parse leaves |d[0][N-1]| in [4, N_NT/2] (non-trivial
                        but not all-terminals).
  config.txt            N, N_NT, N_SIGMA, N_PROD_BIN, N_PROD_TERM, CHUNK_SIZE, SEED,
                        START_SYMBOL, GRAMMAR_SEED.
  dag.bin               Static topology of the parsing wavefront, used by all variants.
                        Header [n_diagonals:u32, total_cells:u64] then per diagonal d in 1..N:
                          [n_cells_in_diag:u32, n_chunks:u32]
                          then n_chunks of: [chunk_id:u32, diag_idx:u32, first_cell_i:u32,
                                             n_cells_in_chunk:u32]
  expected_checksum.txt The Word64 of d[0][N-1] in hexadecimal (uppercase, no 0x prefix).

The DAG topology depends ONLY on N (and CHUNK_SIZE).  This is fundamentally
different from the cascade/N-queens benchmarks where the search shape depends
on data: in CYK every cell (i, j) with i <= j must be computed regardless of
input bytes.  Pre-computing the chunking here is correct.
"""
import argparse, os, struct, sys


N_NT = 64                # non-terminals; each cell is a Word64 bitmask
N_SIGMA = 32             # alphabet
N_PROD_BIN = 1024        # binary productions.  Density high enough for the
                         # random LCG-derived input to parse (below ~700
                         # productions the random parse is empty).  The
                         # bitmask form saturates to popcount=64 within a
                         # few derivation layers, but the k-best variant
                         # bounds per-cell size at TOP_K regardless and
                         # measures meaningful score propagation across the
                         # full parse forest.
N_PROD_TERM_PER_SIGMA = 2  # K terminal producers per symbol
TOP_K = 8                # top-K derivations retained per cell in k-best variant
LOG_PROB_MIN = -10.0     # production log-prob range [LOG_PROB_MIN, 0)
N_PROD_TERM = N_SIGMA * N_PROD_TERM_PER_SIGMA  # 96 total
CHUNK_SIZE_DEFAULT = 32
START_SYMBOL = 0
LCG_A = 6364136223846793005
LCG_C = 1442695040888963407
LCG_MOD = 1 << 63


def lcg_step(r):
    return (LCG_A * r + LCG_C) & (LCG_MOD - 1)


def lcg_stream(seed, count):
    r = seed
    out = []
    for _ in range(count):
        r = lcg_step(r)
        out.append(r)
    return out


def gen_input_bytes(seed, N, alphabet):
    """Same LCG family used by other benchmarks; mod by alphabet on the high bits."""
    out = bytearray(N)
    r = seed
    for i in range(N):
        r = lcg_step(r)
        out[i] = (r >> 33) % alphabet
    return bytes(out)


def gen_grammar(seed):
    """Generate the grammar in TWO complementary representations:

      bitmask form (legacy variant):
        produce_bin[B*N_NT + C] -- Word64 bitmask of A's with A -> B C
        produce_term[sigma]     -- Word64 bitmask of A's with A -> sigma

      list form (k-best variant):
        prods_bin   -- list of (A, B, C, log_prob) tuples, one per binary
                       production.  Production id = index in this list.
        prods_term  -- list of (A, sigma, log_prob) tuples, terminal prods.

    log_prob in [LOG_PROB_MIN, 0).
    """
    produce_bin_mask = [0] * (N_NT * N_NT)
    produce_term_mask = [0] * N_SIGMA
    prods_bin = []
    prods_term = []
    r = seed
    for _ in range(N_PROD_BIN):
        r = lcg_step(r); A = (r >> 33) % N_NT
        r = lcg_step(r); B = (r >> 33) % N_NT
        r = lcg_step(r); C = (r >> 33) % N_NT
        r = lcg_step(r); lp = LOG_PROB_MIN * ((r >> 33) / (1 << 30))
        produce_bin_mask[B * N_NT + C] |= (1 << A)
        prods_bin.append((A, B, C, lp))
    for sigma in range(N_SIGMA):
        for _ in range(N_PROD_TERM_PER_SIGMA):
            r = lcg_step(r); A = (r >> 33) % N_NT
            r = lcg_step(r); lp = LOG_PROB_MIN * ((r >> 33) / (1 << 30))
            produce_term_mask[sigma] |= (1 << A)
            prods_term.append((A, sigma, lp))
    return produce_bin_mask, produce_term_mask, prods_bin, prods_term


def cyk_parse(s, produce_bin, produce_term, N):
    """Reference sequential CYK in Python (BITMASK form).  Used for the
    probe sanity check at small N to confirm grammar+input combination
    is non-trivial."""
    d = [0] * (N * N)
    for i in range(N):
        d[i * N + i] = produce_term[s[i]]
    for span in range(1, N):
        for i in range(N - span):
            j = i + span
            acc = 0
            for k in range(i, j):
                left = d[i * N + k]
                right = d[(k + 1) * N + j]
                lb = left
                while lb:
                    B = (lb & -lb).bit_length() - 1
                    lb &= lb - 1
                    rb = right
                    while rb:
                        C = (rb & -rb).bit_length() - 1
                        rb &= rb - 1
                        acc |= produce_bin[B * N_NT + C]
            d[i * N + j] = acc
    return d


def probe_grammar(probe_N=30):
    """Quick sanity check: parse a probe-length string and report popcount
    of d[0][N-1] (BITMASK form) so we know the grammar+input combo is
    non-trivial.  The k-best variant uses the same grammar."""
    INPUT_SEED = 42
    GRAMMAR_SEED = 43
    s = gen_input_bytes(INPUT_SEED, probe_N, N_SIGMA)
    pb, pt, _, _ = gen_grammar(GRAMMAR_SEED)
    d = cyk_parse(s, pb, pt, probe_N)
    pc = bin(d[0 * probe_N + (probe_N - 1)]).count("1")
    sys.stderr.write(f"[probe] grammar_seed={GRAMMAR_SEED} input_seed={INPUT_SEED} "
                     f"probe_N={probe_N} popcount(d[0][N-1])={pc}\n")
    if pc == 0:
        raise RuntimeError(f"grammar/input combination yields empty parse at probe_N={probe_N}")
    return GRAMMAR_SEED, pc, INPUT_SEED


def emit(out_dir, N, chunk_size):
    os.makedirs(out_dir, exist_ok=True)

    grammar_seed, probe_popcount, input_seed = probe_grammar(probe_N=30)

    # Final grammar + input at the requested N
    produce_bin_mask, produce_term_mask, prods_bin, prods_term = gen_grammar(grammar_seed)
    s = gen_input_bytes(input_seed, N, N_SIGMA)

    with open(os.path.join(out_dir, "input.bin"), "wb") as f:
        f.write(s)

    # grammar.bin: legacy bitmask form, for the bitmask variant.
    # header(4 u32s) + produce_bin(N_NT*N_NT u64) + produce_term(N_SIGMA u64)
    with open(os.path.join(out_dir, "grammar.bin"), "wb") as f:
        f.write(struct.pack("<4I", N_NT, N_SIGMA, N_PROD_BIN, N_PROD_TERM))
        f.write(struct.pack(f"<{N_NT * N_NT}Q", *produce_bin_mask))
        f.write(struct.pack(f"<{N_SIGMA}Q", *produce_term_mask))

    # grammar_prods.bin: k-best variant grammar.
    # header [n_prod_bin:u32, n_prod_term:u32] + n_prod_bin records of
    # (A:u8, B:u8, C:u8, pad:u8, log_prob:f64=8B) totaling 12 bytes each,
    # + n_prod_term records of (A:u8, sigma:u8, pad:u16, log_prob:f64) = 12B.
    with open(os.path.join(out_dir, "grammar_prods.bin"), "wb") as f:
        f.write(struct.pack("<2I", len(prods_bin), len(prods_term)))
        for (A, B, C, lp) in prods_bin:
            f.write(struct.pack("<BBBBd", A, B, C, 0, lp))
        for (A, sigma, lp) in prods_term:
            f.write(struct.pack("<BBHd", A, sigma, 0, lp))

    # dag.bin
    total_cells = N * (N + 1) // 2
    with open(os.path.join(out_dir, "dag.bin"), "wb") as f:
        f.write(struct.pack("<IQ", N - 1, total_cells))  # n_diagonals excludes base diag
        # base diagonal (span=0): N cells, computed before any chunk; not chunked here.
        chunk_id = 0
        for span in range(1, N):
            n_cells_in_diag = N - span
            # diagonals with span < 8 cells get a single chunk
            if span < 8 or n_cells_in_diag <= chunk_size:
                n_chunks = 1
                f.write(struct.pack("<II", n_cells_in_diag, n_chunks))
                f.write(struct.pack("<IIII", chunk_id, span, 0, n_cells_in_diag))
                chunk_id += 1
            else:
                n_chunks = (n_cells_in_diag + chunk_size - 1) // chunk_size
                f.write(struct.pack("<II", n_cells_in_diag, n_chunks))
                for c in range(n_chunks):
                    first = c * chunk_size
                    nc = min(chunk_size, n_cells_in_diag - first)
                    f.write(struct.pack("<IIII", chunk_id, span, first, nc))
                    chunk_id += 1

    # Reference parse in Python is too slow for N>=100 (~O(N^3 * 64^2) ops).
    # The expected_checksum is computed at runtime by cyk_seq_c (the C
    # baseline) and the runner cross-validates other variants against it.
    # Matches the LCS benchmark pattern.
    top = 0

    with open(os.path.join(out_dir, "expected_checksum.txt"), "w") as f:
        f.write(f"{top:016X}\n")

    with open(os.path.join(out_dir, "config.txt"), "w") as f:
        f.write(f"N {N}\n")
        f.write(f"N_NT {N_NT}\n")
        f.write(f"N_SIGMA {N_SIGMA}\n")
        f.write(f"N_PROD_BIN {N_PROD_BIN}\n")
        f.write(f"N_PROD_TERM {N_PROD_TERM}\n")
        f.write(f"CHUNK_SIZE {chunk_size}\n")
        f.write(f"SEED {input_seed}\n")
        f.write(f"GRAMMAR_SEED {grammar_seed}\n")
        f.write(f"START_SYMBOL {START_SYMBOL}\n")
        f.write(f"PROBE_POPCOUNT {probe_popcount}\n")

    print(f"[gen_input] wrote {out_dir}/  N={N} chunk={chunk_size} grammar_seed={grammar_seed} "
          f"probe_popcount={probe_popcount} expected={top:016X}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--N", type=int, required=True)
    ap.add_argument("--chunk-size", type=int, default=CHUNK_SIZE_DEFAULT)
    args = ap.parse_args()
    emit(args.out_dir, args.N, args.chunk_size)


if __name__ == "__main__":
    main()
