#!/usr/bin/env python3
"""Generate CYK parsing benchmark inputs.

Produces in <out-dir>:
  input.bin             N bytes, each in [0, N_SIGMA), LCG seed=42.
  grammar.bin           Header + produce[N_NT*N_NT] (Word64) + produce_term[N_SIGMA] (Word64).
                        Grammar generated by LCG with a separate seed; calibrated so that
                        a small probe parse leaves |d[0][N-1]| in [4, N_NT/2] (non-trivial
                        but not all-terminals).
  config.txt            N, N_NT, N_SIGMA, N_PROD_BIN, N_PROD_TERM, CHUNK_SIZE, SEED,
                        START_SYMBOL, GRAMMAR_SEED.
  dag.bin               Static topology of the parsing wavefront, used by all variants.
                        Header [n_diagonals:u32, total_cells:u64] then per diagonal d in 1..N:
                          [n_cells_in_diag:u32, n_chunks:u32]
                          then n_chunks of: [chunk_id:u32, diag_idx:u32, first_cell_i:u32,
                                             n_cells_in_chunk:u32]
  expected_checksum.txt The Word64 of d[0][N-1] in hexadecimal (uppercase, no 0x prefix).

The DAG topology depends ONLY on N (and CHUNK_SIZE).  This is fundamentally
different from the cascade/N-queens benchmarks where the search shape depends
on data: in CYK every cell (i, j) with i <= j must be computed regardless of
input bytes.  Pre-computing the chunking here is correct.
"""
import argparse, os, struct, sys


N_NT = 64                # non-terminals; each cell is a Word64 bitmask
N_SIGMA = 32             # alphabet
N_PROD_BIN = 1024        # binary productions.  Random CFGs have a sharp
                         # phase transition: below ~700 productions parsing
                         # fails entirely (pc=0); above ~800 the wavefront
                         # saturates to pc=64 within a few derivation layers.
                         # The narrow [4, 32] window the spec asked for is
                         # not robustly achievable with this LCG family.
                         # 1024 sits comfortably above the parse-threshold;
                         # cells saturate to pc=64 but the algorithm still
                         # exercises full O(N^3) bitmask propagation per
                         # cell.  Variants all see the same workload.
N_PROD_TERM_PER_SIGMA = 2  # K terminal producers per symbol
N_PROD_TERM = N_SIGMA * N_PROD_TERM_PER_SIGMA  # 96 total
CHUNK_SIZE_DEFAULT = 32
START_SYMBOL = 0
LCG_A = 6364136223846793005
LCG_C = 1442695040888963407
LCG_MOD = 1 << 63


def lcg_step(r):
    return (LCG_A * r + LCG_C) & (LCG_MOD - 1)


def lcg_stream(seed, count):
    r = seed
    out = []
    for _ in range(count):
        r = lcg_step(r)
        out.append(r)
    return out


def gen_input_bytes(seed, N, alphabet):
    """Same LCG family used by other benchmarks; mod by alphabet on the high bits."""
    out = bytearray(N)
    r = seed
    for i in range(N):
        r = lcg_step(r)
        out[i] = (r >> 33) % alphabet
    return bytes(out)


def gen_grammar(seed):
    """Generate produce_bin[N_NT*N_NT] and produce_term[N_SIGMA].

    produce_bin[B*N_NT + C] is a Word64 bitmask of A's such that A -> B C exists.
    produce_term[sigma] is a Word64 bitmask of A's such that A -> sigma exists.

    Grammar density: N_PROD_BIN productions distributed across N_NT*N_NT (B,C)
    pairs, with each production assigning one A to one (B,C).  Repeats allowed
    (a single (B,C) pair can produce multiple A's, hence the bitmask).  Similarly
    N_PROD_TERM terminal productions across N_SIGMA symbols.
    """
    # IMPORTANT: extract from the HIGH bits of the LCG state.  Low bits of
    # this LCG family have short cycles modulo small powers of two -- using
    # `r % 64` produces only ~64 unique values across 2048 draws.
    produce_bin = [0] * (N_NT * N_NT)
    produce_term = [0] * N_SIGMA
    r = seed
    for _ in range(N_PROD_BIN):
        r = lcg_step(r); A = (r >> 33) % N_NT
        r = lcg_step(r); B = (r >> 33) % N_NT
        r = lcg_step(r); C = (r >> 33) % N_NT
        produce_bin[B * N_NT + C] |= (1 << A)
    # Guarantee every sigma has K terminal producers (avoids "no A -> sigma"
    # holes that would make even tiny strings unparseable).
    for sigma in range(N_SIGMA):
        for _ in range(N_PROD_TERM_PER_SIGMA):
            r = lcg_step(r); A = (r >> 33) % N_NT
            produce_term[sigma] |= (1 << A)
    return produce_bin, produce_term


def cyk_parse(s, produce_bin, produce_term, N):
    """Reference sequential CYK in Python.  Used by calibration on small N
    and (slow) for the expected_checksum on the actual benchmark N."""
    d = [0] * (N * N)
    for i in range(N):
        d[i * N + i] = produce_term[s[i]]
    for span in range(1, N):
        for i in range(N - span):
            j = i + span
            acc = 0
            for k in range(i, j):
                left = d[i * N + k]
                right = d[(k + 1) * N + j]
                # Iterate bits of left, then of right
                lb = left
                while lb:
                    B = (lb & -lb).bit_length() - 1
                    lb &= lb - 1
                    rb = right
                    while rb:
                        C = (rb & -rb).bit_length() - 1
                        rb &= rb - 1
                        acc |= produce_bin[B * N_NT + C]
            d[i * N + j] = acc
    return d


def probe_grammar(probe_N=30):
    """Quick sanity check: parse a probe-length string and report popcount
    so we know the grammar+input combination is non-trivial.  Used purely
    to confirm the LCG-derived grammar at the fixed seed produces a
    parseable string (popcount > 0)."""
    INPUT_SEED = 42
    GRAMMAR_SEED = 43
    s = gen_input_bytes(INPUT_SEED, probe_N, N_SIGMA)
    produce_bin, produce_term = gen_grammar(GRAMMAR_SEED)
    d = cyk_parse(s, produce_bin, produce_term, probe_N)
    pc = bin(d[0 * probe_N + (probe_N - 1)]).count("1")
    sys.stderr.write(f"[probe] grammar_seed={GRAMMAR_SEED} input_seed={INPUT_SEED} "
                     f"probe_N={probe_N} popcount(d[0][N-1])={pc}\n")
    if pc == 0:
        raise RuntimeError(f"grammar/input combination yields empty parse at probe_N={probe_N}")
    return GRAMMAR_SEED, pc, INPUT_SEED


def emit(out_dir, N, chunk_size):
    os.makedirs(out_dir, exist_ok=True)

    grammar_seed, probe_popcount, input_seed = probe_grammar(probe_N=30)

    # Final grammar + input at the requested N
    produce_bin, produce_term = gen_grammar(grammar_seed)
    s = gen_input_bytes(input_seed, N, N_SIGMA)

    with open(os.path.join(out_dir, "input.bin"), "wb") as f:
        f.write(s)

    # grammar.bin: header(4 u32s) + produce_bin(N_NT*N_NT u64) + produce_term(N_SIGMA u64)
    with open(os.path.join(out_dir, "grammar.bin"), "wb") as f:
        f.write(struct.pack("<4I", N_NT, N_SIGMA, N_PROD_BIN, N_PROD_TERM))
        f.write(struct.pack(f"<{N_NT * N_NT}Q", *produce_bin))
        f.write(struct.pack(f"<{N_SIGMA}Q", *produce_term))

    # dag.bin
    total_cells = N * (N + 1) // 2
    with open(os.path.join(out_dir, "dag.bin"), "wb") as f:
        f.write(struct.pack("<IQ", N - 1, total_cells))  # n_diagonals excludes base diag
        # base diagonal (span=0): N cells, computed before any chunk; not chunked here.
        chunk_id = 0
        for span in range(1, N):
            n_cells_in_diag = N - span
            # diagonals with span < 8 cells get a single chunk
            if span < 8 or n_cells_in_diag <= chunk_size:
                n_chunks = 1
                f.write(struct.pack("<II", n_cells_in_diag, n_chunks))
                f.write(struct.pack("<IIII", chunk_id, span, 0, n_cells_in_diag))
                chunk_id += 1
            else:
                n_chunks = (n_cells_in_diag + chunk_size - 1) // chunk_size
                f.write(struct.pack("<II", n_cells_in_diag, n_chunks))
                for c in range(n_chunks):
                    first = c * chunk_size
                    nc = min(chunk_size, n_cells_in_diag - first)
                    f.write(struct.pack("<IIII", chunk_id, span, first, nc))
                    chunk_id += 1

    # Reference parse in Python is too slow for N>=100 (~O(N^3 * 64^2) ops).
    # The expected_checksum is computed at runtime by cyk_seq_c (the C
    # baseline) and the runner cross-validates other variants against it.
    # Matches the LCS benchmark pattern.
    top = 0

    with open(os.path.join(out_dir, "expected_checksum.txt"), "w") as f:
        f.write(f"{top:016X}\n")

    with open(os.path.join(out_dir, "config.txt"), "w") as f:
        f.write(f"N {N}\n")
        f.write(f"N_NT {N_NT}\n")
        f.write(f"N_SIGMA {N_SIGMA}\n")
        f.write(f"N_PROD_BIN {N_PROD_BIN}\n")
        f.write(f"N_PROD_TERM {N_PROD_TERM}\n")
        f.write(f"CHUNK_SIZE {chunk_size}\n")
        f.write(f"SEED {input_seed}\n")
        f.write(f"GRAMMAR_SEED {grammar_seed}\n")
        f.write(f"START_SYMBOL {START_SYMBOL}\n")
        f.write(f"PROBE_POPCOUNT {probe_popcount}\n")

    print(f"[gen_input] wrote {out_dir}/  N={N} chunk={chunk_size} grammar_seed={grammar_seed} "
          f"probe_popcount={probe_popcount} expected={top:016X}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--N", type=int, required=True)
    ap.add_argument("--chunk-size", type=int, default=CHUNK_SIZE_DEFAULT)
    args = ap.parse_args()
    emit(args.out_dir, args.N, args.chunk_size)


if __name__ == "__main__":
    main()
