#!/usr/bin/env python3
"""Generate the Haskell sequential baseline for the full transformer-block
attention end-to-end. Monolithic single-thread, NO parallelism: this is the
Haskell-tier denominator (T_seq) against which Ribault-Hs and GHC Strategies
report their speedups.

Storage idiom: IOVector Storable Double (Data.Vector.Storable.Mutable),
identical to gen_attn_hs_strategies.py — same compute backend, same memory
layout, same RTS allocator. The only thing that changes vs STRAT is the
absence of parList rseq and the absence of the per-block row decomposition:
this baseline runs the kernels as one flat full-N pass.

Cross-validation: the printed CHECKSUM= must equal expected_checksum.txt
generated by gen_attn_data.py (the numpy reference).
"""

import argparse, os


HS_TEMPLATE = r"""{-# LANGUAGE BangPatterns #-}
module Main where

-- Attention sequential baseline (full end-to-end transformer block).
-- Monolithic single-thread. SAME compute backend as the GHC Strategies
-- variant (Data.Vector.Storable.Mutable Double) to keep the denominator
-- on the same compute idiom as the parallel numerator; the only
-- difference is the absence of parList rseq and the absence of block
-- decomposition.

import Control.Monad (forM_)
import Data.Word (Word8)
import Data.Bits ((.&.))
import qualified Data.ByteString as BS
import qualified Data.ByteString.Internal as BSI
import qualified Data.Vector.Storable.Mutable as MV
import Foreign.ForeignPtr (withForeignPtr)
import Foreign.Ptr (Ptr, plusPtr)
import Foreign.Storable (peek)
import Data.Time.Clock (getCurrentTime, diffUTCTime)
import System.IO (hFlush, stdout)

attnN, attnD, attnHeads, attnHeadDim, attnDff, attnVocab :: Int
attnN       = __N__
attnD       = __D__
attnHeads   = __N_HEADS__
attnHeadDim = __HEAD_DIM__
attnDff     = __D_FF__
attnVocab   = __VOCAB__

dataDir :: FilePath
dataDir = "__DATA_DIR__"

readDoubles :: FilePath -> Int -> IO (MV.IOVector Double)
readDoubles path count = do
  bs <- BS.readFile path
  let !(BSI.BS fp _) = bs
  v <- MV.replicate count 0.0
  withForeignPtr fp $ \src -> do
    forM_ [0..count-1] $ \i -> do
      !d <- peek (src `plusPtr` (i*8) :: Ptr Double)
      MV.write v i d
  return v

readBytes :: FilePath -> Int -> IO (MV.IOVector Word8)
readBytes path count = do
  bs <- BS.readFile path
  let !(BSI.BS fp _) = bs
  v <- MV.replicate count 0
  withForeignPtr fp $ \src -> do
    forM_ [0..count-1] $ \i -> do
      !w <- peek (src `plusPtr` i :: Ptr Word8)
      MV.write v i w
  return v

-- Full-N matmul:  C[M,N_dim] = A[M,K_dim] @ B[K_dim,N_dim]
matmulAll :: Int -> Int -> Int -> MV.IOVector Double -> MV.IOVector Double
          -> MV.IOVector Double -> IO ()
matmulAll !mDim !kDim !nDim !a !b !c =
  forM_ [0..mDim-1] $ \m -> do
    forM_ [0..nDim-1] $ \n -> MV.write c (m*nDim + n) 0.0
    forM_ [0..kDim-1] $ \k -> do
      !av <- MV.read a (m*kDim + k)
      forM_ [0..nDim-1] $ \n -> do
        !bv <- MV.read b (k*nDim + n)
        !cv <- MV.read c (m*nDim + n)
        MV.write c (m*nDim + n) (cv + av*bv)

-- Full-N layer norm:  out[i,:] = (x[i,:] - mean) / sqrt(var + eps) * w + b
layerNormAll :: Int -> Int -> MV.IOVector Double -> MV.IOVector Double
             -> MV.IOVector Double -> MV.IOVector Double -> IO ()
layerNormAll !rows !dim !x !w !b !out = do
  let eps = 1e-5
  forM_ [0..rows-1] $ \i -> do
    !mu <- meanOver x (i*dim) dim
    !var <- varOver x (i*dim) dim mu
    let !inv = 1.0 / sqrt (var + eps)
    forM_ [0..dim-1] $ \j -> do
      !v <- MV.read x (i*dim + j)
      !wj <- MV.read w j
      !bj <- MV.read b j
      MV.write out (i*dim + j) ((v - mu) * inv * wj + bj)
  where
    meanOver !v !base !d = do
      let go !i !acc
            | i >= d    = return (acc / fromIntegral d)
            | otherwise = do
                !x' <- MV.read v (base + i)
                go (i+1) (acc + x')
      go 0 0.0
    varOver !v !base !d !mu = do
      let go !i !acc
            | i >= d    = return (acc / fromIntegral d)
            | otherwise = do
                !x' <- MV.read v (base + i)
                let !dd = x' - mu
                go (i+1) (acc + dd*dd)
      go 0 0.0

main :: IO ()
main = do
  e      <- readDoubles (dataDir ++ "/E.bin")      (attnVocab * attnD)
  peM    <- readDoubles (dataDir ++ "/PE.bin")     (attnN     * attnD)
  wQ     <- readDoubles (dataDir ++ "/W_Q.bin")    (attnD     * attnD)
  wK     <- readDoubles (dataDir ++ "/W_K.bin")    (attnD     * attnD)
  wV     <- readDoubles (dataDir ++ "/W_V.bin")    (attnD     * attnD)
  wO     <- readDoubles (dataDir ++ "/W_O.bin")    (attnD     * attnD)
  w1     <- readDoubles (dataDir ++ "/W_1.bin")    (attnD     * attnDff)
  w2     <- readDoubles (dataDir ++ "/W_2.bin")    (attnDff   * attnD)
  wU     <- readDoubles (dataDir ++ "/W_U.bin")    (attnD     * attnVocab)
  ln1w   <- readDoubles (dataDir ++ "/LN_1_w.bin") attnD
  ln1b   <- readDoubles (dataDir ++ "/LN_1_b.bin") attnD
  ln2w   <- readDoubles (dataDir ++ "/LN_2_w.bin") attnD
  ln2b   <- readDoubles (dataDir ++ "/LN_2_b.bin") attnD
  inputT <- readBytes   (dataDir ++ "/input_tokens.bin") attnN
  outputT<- MV.replicate attnN (0 :: Word8)

  xBuf   <- MV.replicate (attnN * attnD)     0.0
  xaBuf  <- MV.replicate (attnN * attnD)     0.0
  qBuf   <- MV.replicate (attnN * attnD)     0.0
  kBuf   <- MV.replicate (attnN * attnD)     0.0
  vBuf   <- MV.replicate (attnN * attnD)     0.0
  attnB  <- MV.replicate (attnN * attnD)     0.0
  xbBuf  <- MV.replicate (attnN * attnD)     0.0
  ffnH   <- MV.replicate (attnN * attnDff)   0.0
  logits <- MV.replicate (attnN * attnVocab) 0.0
  scores <- MV.replicate attnN               0.0

  t0 <- getCurrentTime

  -- embed + sinusoidal pos
  forM_ [0..attnN-1] $ \i -> do
    !tok <- fromIntegral <$> MV.read inputT i
    forM_ [0..attnD-1] $ \j -> do
      !ev <- MV.read e (tok*attnD + j)
      !pv <- MV.read peM (i*attnD + j)
      MV.write xBuf (i*attnD + j) (ev + pv)

  -- LN_1
  layerNormAll attnN attnD xBuf ln1w ln1b xaBuf

  -- Q/K/V projections
  matmulAll attnN attnD attnD xaBuf wQ qBuf
  matmulAll attnN attnD attnD xaBuf wK kBuf
  matmulAll attnN attnD attnD xaBuf wV vBuf

  -- Multi-head attention
  let !inv = 1.0 / sqrt (fromIntegral attnHeadDim)
  forM_ [0..attnN-1] $ \i ->
    forM_ [0..attnD-1] $ \j -> MV.write attnB (i*attnD + j) 0.0
  forM_ [0..attnN-1] $ \i ->
    forM_ [0..attnHeads-1] $ \h -> do
      forM_ [0..attnN-1] $ \j -> do
        let go !k !acc
              | k >= attnHeadDim = return acc
              | otherwise = do
                  !q  <- MV.read qBuf (i*attnD + h*attnHeadDim + k)
                  !kv <- MV.read kBuf (j*attnD + h*attnHeadDim + k)
                  go (k+1) (acc + q*kv)
        !s <- go 0 0.0
        MV.write scores j (s * inv)
      !mx0 <- MV.read scores 0
      let goMax !ii !m
            | ii >= attnN = return m
            | otherwise = do
                !v <- MV.read scores ii
                goMax (ii+1) (max m v)
      !mx <- goMax 1 mx0
      let goSum !ii !acc
            | ii >= attnN = return acc
            | otherwise = do
                !v <- MV.read scores ii
                let !ev = exp (v - mx)
                MV.write scores ii ev
                goSum (ii+1) (acc + ev)
      !sm <- goSum 0 0.0
      forM_ [0..attnN-1] $ \j -> do
        !v <- MV.read scores j
        MV.write scores j (v / sm)
      forM_ [0..attnN-1] $ \j -> do
        !a <- MV.read scores j
        forM_ [0..attnHeadDim-1] $ \k -> do
          !vv  <- MV.read vBuf (j*attnD + h*attnHeadDim + k)
          !cur <- MV.read attnB (i*attnD + h*attnHeadDim + k)
          MV.write attnB (i*attnD + h*attnHeadDim + k) (cur + a*vv)

  -- attn @ W_O + residual
  matmulAll attnN attnD attnD attnB wO xaBuf
  forM_ [0..attnN-1] $ \i ->
    forM_ [0..attnD-1] $ \j -> do
      !xv <- MV.read xBuf  (i*attnD + j)
      !yv <- MV.read xaBuf (i*attnD + j)
      MV.write xBuf (i*attnD + j) (xv + yv)

  -- LN_2
  layerNormAll attnN attnD xBuf ln2w ln2b xbBuf

  -- FFN: xb @ W_1 -> ReLU -> @ W_2 + residual
  matmulAll attnN attnD attnDff xbBuf w1 ffnH
  forM_ [0..attnN-1] $ \i ->
    forM_ [0..attnDff-1] $ \j -> do
      !v <- MV.read ffnH (i*attnDff + j)
      MV.write ffnH (i*attnDff + j) (if v < 0 then 0 else v)
  matmulAll attnN attnDff attnD ffnH w2 xaBuf
  forM_ [0..attnN-1] $ \i ->
    forM_ [0..attnD-1] $ \j -> do
      !xv <- MV.read xBuf  (i*attnD + j)
      !yv <- MV.read xaBuf (i*attnD + j)
      MV.write xBuf (i*attnD + j) (xv + yv)

  -- Unembed + argmax
  matmulAll attnN attnD attnVocab xBuf wU logits
  forM_ [0..attnN-1] $ \i -> do
    !l0 <- MV.read logits (i*attnVocab + 0)
    let goArg !v !bestV !bestVal
          | v >= attnVocab = return bestV
          | otherwise = do
              !lv <- MV.read logits (i*attnVocab + v)
              if lv > bestVal then goArg (v+1) v lv
                              else goArg (v+1) bestV bestVal
    !best <- goArg 1 0 l0
    MV.write outputT i (fromIntegral best :: Word8)

  t1 <- getCurrentTime
  let !secs = realToFrac (diffUTCTime t1 t0) :: Double

  -- Checksum
  let goCs !i !acc
        | i >= attnN = return ((acc :: Word) .&. 0xFFFFFFFF)
        | otherwise = do
            !w <- MV.read outputT i
            goCs (i+1) (acc + fromIntegral (i+1) * fromIntegral w)
  !cs <- goCs 0 0
  putStrLn $ "CHECKSUM=" ++ show cs
  putStrLn $ "RUNTIME_SEC=" ++ show secs
  hFlush stdout
"""


def emit(out_path, data_dir, N, D, n_heads, head_dim, d_ff, vocab):
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    src = (HS_TEMPLATE
           .replace("__N__", str(N))
           .replace("__D__", str(D))
           .replace("__N_HEADS__", str(n_heads))
           .replace("__HEAD_DIM__", str(head_dim))
           .replace("__D_FF__", str(d_ff))
           .replace("__VOCAB__", str(vocab))
           .replace("__DATA_DIR__", data_dir))
    with open(out_path, "w") as f:
        f.write(src)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--data-dir", required=True)
    args = ap.parse_args()

    cfg = {}
    with open(os.path.join(args.data_dir, "config.txt")) as f:
        for line in f:
            k, v = line.split()
            cfg[k] = int(v)
    emit(args.out, os.path.abspath(args.data_dir),
         cfg["N"], cfg["D"], cfg["N_HEADS"], cfg["HEAD_DIM"], cfg["D_FF"], cfg["VOCAB"])


if __name__ == "__main__":
    main()
