#!/usr/bin/env bash
set -euo pipefail

# Ensure UTF-8 locale (Sucuri/maturin/cargo may need it).
export LANG="${LANG:-C.utf8}"
export LC_ALL="${LC_ALL:-C.utf8}"

# ============================================================
# LCS Wavefront — Sucuri sweep (Tiago's dataflow lib)
#
# Runs only the Sucuri variant on top of the existing input
# generated by the main LCS runner. Sequences, DIM_COLS auto
# scaling, seq baseline timing, P sweep, REPS, taskset pinning —
# all identical to what the Haskell variants get. Adds rows with
# variant="sucuri" to a CSV the main runner's metrics.csv format.
# ============================================================

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
OUTROOT="${1:-$REPO/results/lcs_wavefront_sucuri}"
mkdir -p "$OUTROOT"
OUTROOT="$(cd "$OUTROOT" && pwd)"

GEN_INPUT="$REPO/scripts/lcs_wavefront/gen_input.py"

# Sucuri install (compiled python3.14t free-threading + Rust crate).
SUCURI_ROOT="${SUCURI_ROOT:-$HOME/Sucuri}"
PYTHON_NOGIL="${PYTHON_NOGIL:-$HOME/python3.14t/bin/python3.14t}"
PYTHON_LIBDIR="${PYTHON_LIBDIR:-$HOME/python3.14t/lib}"
SUCURI_DRIVER="$SUCURI_ROOT/run_sucuri_lcs.py"

[[ -x "$PYTHON_NOGIL" ]] || { echo "FATAL: $PYTHON_NOGIL not executable"; exit 1; }
[[ -d "$SUCURI_ROOT" ]] || { echo "FATAL: SUCURI_ROOT not found: $SUCURI_ROOT"; exit 1; }
[[ -f "$SUCURI_DRIVER" ]] || { echo "FATAL: driver missing: $SUCURI_DRIVER"; exit 1; }

REPS=${REPS:-7}
SEED=${SEED:-42}
ALPHABET=${ALPHABET:-4}
NS=(${NS:-200000})
PS=(${PS:-1 2 4 8 16 24 32 40 48})
DIM_COLS=${DIM_COLS:-auto}
TARGET_BLOCK_WIDTH=${TARGET_BLOCK_WIDTH:-1000}

N_PHYS_CORES=${N_PHYS_CORES:-24}
N_LOG_CORES=${N_LOG_CORES:-48}

pin_cores() {
  local p="$1"
  if (( p > N_LOG_CORES )); then echo "0-$((N_LOG_CORES - 1))"; else echo "0-$((p - 1))"; fi
}
pin_tag() {
  local p="$1"
  if (( p <= N_PHYS_CORES )); then
    echo "physical, cores 0-$((p-1)), no HT"
  else
    local ht=$(( p - N_PHYS_CORES ))
    echo "oversubscribed, cores 0-$((p-1)) = $N_PHYS_CORES phys + $ht HT siblings"
  fi
}
OS_BANNER_SHOWN=0

validate() {
  local label="$1" file="$2" expected="$3"
  local got
  got="$(awk -F= '/^RESULT=/{print $2}' "$file" 2>/dev/null || true)"
  if [[ -z "$got" ]]; then
    echo "FATAL: $label -> no RESULT= found in $file"; cat "$file" 2>/dev/null || true; exit 1
  fi
  if [[ "$expected" == "SKIP" ]]; then
    if [[ -z "${CROSS_EXPECTED:-}" ]]; then
      CROSS_EXPECTED="$got"; echo "  OK: RESULT=$got (first result, will cross-validate)"
    elif [[ "$got" != "$CROSS_EXPECTED" ]]; then
      echo "FATAL: $label -> got $got, expected $CROSS_EXPECTED (cross-validate)"; exit 1
    else
      echo "  OK: RESULT=$got (cross-validated)"
    fi
  else
    if [[ "$got" != "$expected" ]]; then
      echo "FATAL: $label -> got $got, expected $expected"; exit 1
    fi
    echo "  OK: RESULT=$got (correct)"
  fi
}

CSV="$OUTROOT/metrics.csv"
echo "variant,seq_len,dim_rows,dim_cols,P,rep,seconds" > "$CSV"

echo "================================================================"
echo " LCS Wavefront — Sucuri sweep (rectangular grid, equal-footing)"
echo "================================================================"
echo " Workload params:"
echo "   NS (seq_len)=${NS[*]}  DIM_ROWS=P  DIM_COLS=$DIM_COLS  ALPHABET=$ALPHABET"
echo "   reps=$REPS  seed=$SEED"
echo ""
echo " Sucuri runtime:"
echo "   python: $PYTHON_NOGIL (free-threading no-GIL)"
echo "   compute backend: Rust (sucuri_lcs crate)"
echo "   scheduler: threads engine, n_workers=P"
echo ""
echo " Methodological equivalence preserved:"
echo "   * Same input sequences (LCG seed=$SEED) as Haskell variants"
echo "   * Same rectangular grid DIM_ROWS x DIM_COLS as TALM"
echo "   * Same P sweep, REPS=$REPS, taskset -c 0..(P-1)"
echo "   * Same seq baseline (cross-validation against TALM/STRAT/PARPSEQ)"
echo ""
echo " P sweep: ${PS[*]}"
echo "================================================================"

for N in "${NS[@]}"; do
  echo ""
  echo "############################################"
  echo "# SEQ_LEN=$N"
  echo "############################################"

  NDIR="$OUTROOT/N_${N}"
  mkdir -p "$NDIR"
  CROSS_EXPECTED=""

  INPUT_DIR="$NDIR/input"
  python3 "$GEN_INPUT" --N "$N" --alphabet "$ALPHABET" --seed "$SEED" \
      --out-dir "$INPUT_DIR"
  EXPECTED="$(cat "$INPUT_DIR/expected.txt")"
  echo "  Expected LCS score: $EXPECTED"

  for P in "${PS[@]}"; do
    if [[ "$P" -gt "$N_PHYS_CORES" && "$OS_BANNER_SHOWN" -eq 0 ]]; then
      echo ""
      echo "  ################################################################"
      echo "  ##  OVERSUBSCRIPTION BEGINS HERE                              ##"
      echo "  ##  Next P values exceed $N_PHYS_CORES physical cores         ##"
      echo "  ################################################################"
      OS_BANNER_SHOWN=1
    fi

    CUR_ROWS=$P
    if [[ "$DIM_COLS" == "auto" ]]; then
      CUR_COLS=$(( N / TARGET_BLOCK_WIDTH ))
      if (( CUR_COLS < P )); then CUR_COLS=$P; fi
    else
      CUR_COLS=$DIM_COLS
    fi
    TOTAL_BLOCKS=$((CUR_ROWS * CUR_COLS))
    CORES_P="$(pin_cores "$P")"
    PIN_TAG="$(pin_tag "$P")"
    echo ""
    echo "======== SEQ_LEN=$N  P=$P  grid=${CUR_ROWS}x${CUR_COLS} (${TOTAL_BLOCKS} blocks; cores: $CORES_P; $PIN_TAG) ========"

    SDIR="$NDIR/sucuri_P${P}"
    mkdir -p "$SDIR"

    for ((rep=1; rep<=REPS; rep++)); do
      OUT="$SDIR/out_P${P}_r${rep}.txt"
      ERR="$SDIR/err_P${P}_r${rep}.txt"

      # PYTHON_GIL=0 forces no-GIL for python3.14t; the sucuri_lcs Rust module
      # was built before free-threading PEP 703 was declared, so without this
      # env var the runtime would re-enable the GIL.
      SUCURI_ROOT="$SUCURI_ROOT" \
        LD_LIBRARY_PATH="$PYTHON_LIBDIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
        PYTHON_GIL=0 \
        taskset -c "$CORES_P" \
          "$PYTHON_NOGIL" "$SUCURI_DRIVER" \
            --input-dir "$INPUT_DIR" \
            --workers "$P" \
            --dim-rows "$CUR_ROWS" \
            --dim-cols "$CUR_COLS" \
            --backend rust \
          > "$OUT" 2> "$ERR"
      secs="$(awk -F= '/^RUNTIME_SEC=/{print $2}' "$OUT")"
      echo "SUCURI   N=$N P=$P ${CUR_ROWS}x${CUR_COLS} rep=$rep -> ${secs}s"
      validate "SUCURI N=$N P=$P rep=$rep" "$OUT" "$EXPECTED"
      echo "sucuri,$N,$CUR_ROWS,$CUR_COLS,$P,$rep,$secs" >> "$CSV"
    done
  done
done

echo ""
echo "================================================================"
echo " SUCURI SWEEP COMPLETED"
echo " CSV: $CSV"
echo "================================================================"
