#!/usr/bin/env python3
"""Generate TALM .hsk for 0/1 Knapsack solved via parallel merge-sort aggregation.

The algorithm:
  1. Enumerate ALL 2^N subsets, compute each subset's value (0 if infeasible)
  2. Sort the values (descending) using parallel merge sort
  3. Maximum = head of sorted list = optimal knapsack value

Uses the COARSE merge-sort template (same structure that gives TALM its
dataflow scheduling advantage): init_super + split/merge/sort supers +
recursive mergeSortD tree.

Requires DF_LIST_BUILTIN=1 for C-list encoding.
"""

import argparse, os, math


def compute_depth(n, cutoff):
    if n <= cutoff:
        return 0
    return 1 + compute_depth(n // 2, cutoff)


def emit_hsk(path, items_dir, n_items, nparts):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)

    total_subsets = 2 ** n_items

    items = []
    with open(os.path.join(items_dir, "items.txt")) as f:
        for line in f:
            w, v = line.split()
            items.append((int(w), int(v)))
    with open(os.path.join(items_dir, "capacity.txt")) as f:
        capacity = int(f.read().strip())

    cutoff = max(1, total_subsets // nparts)
    depth = compute_depth(total_subsets, cutoff)

    hsk = f"""-- knapsack_mergesort.hsk (auto-generated)
-- N_ITEMS={n_items}  CAPACITY={capacity}  TOTAL={total_subsets}
-- nparts={nparts}  depth={depth}  cutoff={cutoff}
-- Solving Subset Sum via parallel merge-sort aggregation

-- init_super: build the vector of ALL subset values inside Haskell
-- Input: 1-element C-list [total_subsets]
-- Output: C-list of total_subsets Int64 values (each = subset value or 0)
init_super inp =
  super single input (inp) output (result)
#BEGINSUPER
    result = let
        hlist = ctoList inp
        n = fromIntegral (head hlist) :: Int
      in cfromList (ksGenerateValues n)
#ENDSUPER;

-- split_super: list -> [leftHandle, rightHandle]
split_super lst =
  super single input (lst) output (result)
#BEGINSUPER
    result =
      let
        hlist = ctoList lst
        sp []         = ([], [])
        sp [x]        = ([x], [])
        sp (x:y:rest) = let (xs, ys) = sp rest in (x:xs, y:ys)
        (l, r) = sp hlist
      in cfromList [cfromList l, cfromList r]
#ENDSUPER;

-- merge_super: merge two sorted (descending) C-lists
merge_super pair =
  super single input (pair) output (result)
#BEGINSUPER
    result =
      let
        hpair = ctoList pair
        l  = ctoList (head hpair)
        r  = ctoList (head (tail hpair))
        mg [] ys        = ys
        mg xs []        = xs
        mg (x:xt) (y:yt)
          | x >= y     = x : mg xt (y:yt)
          | otherwise  = y : mg (x:xt) yt
      in cfromList (mg l r)
#ENDSUPER;

-- ms_super: leaf sort (sequential merge sort, descending)
ms_super lst =
  super single input (lst) output (sorted)
#BEGINSUPER
    sorted =
      let
        hlist = ctoList lst

        splitLocal []         = ([], [])
        splitLocal [x]        = ([x], [])
        splitLocal (x:y:rest) =
          let (xs, ys) = splitLocal rest
          in (x:xs, y:ys)

        mergeLocal [] ys        = ys
        mergeLocal xs []        = xs
        mergeLocal (x:xt) (y:yt)
          | x >= y              = x : mergeLocal xt (y:yt)
          | otherwise           = y : mergeLocal (x:xt) yt

        ms []  = []
        ms [x] = [x]
        ms xs  =
          let (l, r) = splitLocal xs
          in mergeLocal (ms l) (ms r)
      in
        cfromList (ms hlist)
#ENDSUPER;

-- print_result: extract max (head of descending-sorted list), print RESULT=
print_result lst =
  super single input (lst) output (out)
#BEGINSUPER
    out = unsafePerformIO $ do
      let pHead p = peekByteOff (intPtrToPtr (fromIntegral p)) 0 :: IO Int64
      if lst == 0
        then do putStrLn "RESULT=0"; hFlush stdout; pure 0
        else do
          maxVal <- pHead lst
          putStrLn ("RESULT=" ++ show maxVal)
          hFlush stdout
          pure 0
#ENDSUPER;

-- Recursive merge-sort tree (same structure as merge sort benchmark)
mergeSortD d lst =
    if d <= 0
    then ms_super lst
    else
      case split_super lst of
        (lh : rest) -> case rest of
          (rh : _) ->
            merge_super (mergeSortD (d - 1) lh : mergeSortD (d - 1) rh : []);;
;

main = print_result (mergeSortD {depth} (init_super [{total_subsets}]));
"""

    with open(path, "w", encoding="utf-8") as f:
        f.write(hsk)
    print(f"[gen_ks_ms_talm] wrote {path}  (n_items={n_items}, total={total_subsets}, "
          f"nparts={nparts}, depth={depth})")

    # Generate supers_inject.hs
    inject_path = os.path.join(os.path.dirname(path) or ".", "supers_inject.hs")
    items_literal = "[" + ", ".join(f"({w},{v})" for w, v in items) + "]"

    inject = f"""
-- Knapsack value generation (auto-generated by gen_talm_input.py)
-- Evaluates all 2^N subsets for brute-force 0/1 Knapsack.

ksItems :: [(Int, Int)]
ksItems = {items_literal}

ksCapacity :: Int
ksCapacity = {capacity}

-- Evaluate one subset by walking bits against the item list.
ksEvalSubset :: Int -> Int
ksEvalSubset s = go ksItems s 0 0
  where
    go [] _ !tw !tv
      | tw <= ksCapacity = tv
      | otherwise        = 0
    go _ 0 !tw !tv
      | tw <= ksCapacity = tv
      | otherwise        = 0
    go ((w,v):rest) !bits !tw !tv
      | bits `mod` 2 == 1 = go rest (bits `div` 2) (tw+w) (tv+v)
      | otherwise          = go rest (bits `div` 2) tw tv

-- Generate all subset values as a list (called by init_super)
ksGenerateValues :: Int -> [Int64]
ksGenerateValues n = [fromIntegral (ksEvalSubset i) | i <- [0..n-1]]
"""
    with open(inject_path, "w", encoding="utf-8") as f:
        f.write(inject)
    print(f"[gen_ks_ms_talm] wrote {inject_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--items-dir", required=True)
    ap.add_argument("--n-items", type=int, required=True)
    ap.add_argument("--nparts", type=int, default=64,
                    help="Number of parallel leaf chunks (default 64)")
    args = ap.parse_args()
    emit_hsk(args.out, args.items_dir, args.n_items, args.nparts)


if __name__ == "__main__":
    main()
